version: '3.9'

services:
  nginx:
    container_name: nginx
    build: ./
    restart: on-failure
    ports:
      - '80:80'
      - '443:433'
    tty: true

  api:
    container_name: api
    build: ./api
    restart: on-failure
    ports:
      - '7555:7555'
